### ISSUE TITLE
Add a config option to limit the # of records searched while betting

### ISSUE THREAD

**Issue by ACIIL** [saltbot-org/saltbot#144]
Glad i found this now. It's probably important to put this in the user documentation. And if is already was good.

saltyBot only remember the last 15 matches for a character.  This function
`limitRecordsTo(c1Obj, 15);`
Is called after every character match update in
`Updater.prototype.updateCharactersFromMatch = function (mObj, c1Obj, c2Obj) `
Which is the function called every time a new match record is recorded, like importing records. end of match, etc...

It means some important things for data miners.  Such as, Is you characters' last 15 matches recent?  
And it means characters getting buffed/nerfed is now sorta reflected in the recent history.

The user documentation needs this note: only the last few matches are kept for prediction. (currently hard coded 15).

From the programmer side, could this method be improved?  Is the export button stripping away all the now out of date matches the limit_records would remove as it reads in new matches in run-time?   Do we really need +50k match records if a good chuck is out of date character matches? How would we removed old matches that no longer reflects the two characters' recent last 15 matches?

**Comment by ACIIL** [comment]
Its also means chromosome training does not reflect all the match data. I will try to explain.

CSStats()  combines a characters stats (last 15)  to the chromosome and makes tier based scores of its record.

Then there are two CSStats, for Character1 & Character2, which uses further chromosome weights to finalize score between them.

This score is used for confidence, the prediction, which is used BOTH for:
1) predicting winner of current match on salty bet.
2) evaluating if the chromosome predictions are correct. Which requires comparing data on ALL match records.

The issue in number 2), the prediction (based on last recent 15 character records), against all matches that used this character.   There is a good chance if the character is recently changed (and reflected in the last 15 matches), the prediction of all its recorded matches of that character no longer reflects it.

This also part of that error range when testing the heuristic of how accuracy or money gaining a chromosome is.

**Comment by ACIIL** [comment]
Further study taught some interesting things.  Records for the different types of stats:  win %, average time, odds, etc.  They are independent arrays saved, they need not be in sync, nor the sample sizes are going to be equal/recorded for each match record.

So for example a tournament match data retains the winner, and then that new (W:L) sample is pushed into the winnings stat of the characters. The other samples for time, odds, etc, may not exist and not be pushed into the characters data.

These separate sample sizes adds a layer of caution to character stats, as you still need n+ samples of each stat type before the bot bets accurately. There are no penalties for low samples of all the stats. Not to mention when characters get (de)buffed.

For an example of caution, a tourney match will not update character times, so for a relatively new character, you will see its winning % better sampled, but the bot is still using low sampled times that came from outside the tourney(match making), and retains whatever time outliners there are to ruin precision. ( forgot if odds samples update in tourney matches)

In relation to issue #126 , i also found out 0 times are not added to the characters time stat samples, so time outliners are not created from 0's, you just have poor match records. Some character stats will get the ugly 'U' tier. 'U' can come from anywhere and any tier, they are wildcards, and the bot has to train an average to predict them accurately. You will never get a 100% accurate bot as long as 'U''s are recorded.

Currently thinking of ways to temper the character stats with low sample sizes, such that the bot will bet more moderate. I got some math equations in testing.

**Comment by reconman** [comment]
This feature of only taking that last 15 matches was implemented by me and was not part of the inital design.

I'm having a hard time understanding all your issues with the current code with the 3 wall of texts. Can you please point out parts of the code which do not work correctly / could be improved? Without that only you will know what to change.

**Comment by ACIIL** [comment]
Overview:   Stats and sample sizes used better for more accurate prediction. The topic is heavy and i am sorry i cannot simplify it, but i will try.
- the sample size is is pulled from 15 matches. The bot is aware of only the only the last 15 matches per character (bit more detail in a sec).
- Each character runs on samples for: win rate, time, odds, etc.  This affect how the bot bets. Its behavior can explain some strange predictions, which would be easier to explain when sample sizes are logged.
- Samples are not all pushed into a character after a match, as some matches cannot record everything. It must be clear samples update independently. (an examples have been written above for tournaments).
- Character data sample size and how outliers in the stats are dealt with.  My solution is to increase the sample size (increase the cap).
- The sample size should be a user defined setting. The setting comes in effect at import or new match records. (tested the update moment)
- Low sample sizes and making the bot be conservative when so. I been experimenting with this.  (example; for each sample at a % below max sample size, penalized the confidence more.) Confidence is defined as that 50% to 100% bet modifier given before each match.
- Printing sample sizes for each type in the console. I have some ideas, it requires some new sample size variables in `CSStats` to be populated and used in the confidence adjustment.
- 'U' tiers are useless. Its just failed match data that should not be recorded. At best the "win" or 'time' record may still exist. 
- Tournament matches are 'U' tier, following that only win records are recorded.   These matches provide little beneficial stat data and means the bot does not adapt to tournaments each round

**Comment by calexil** [comment]
@reconman time to revisit this info

**Comment by calexil** [comment]
Sorry for the delay on this, I have been very busy streaming and getting my car fixed and registered. 

Once I find free time I'll get on it.

**Comment by calexil** [comment]
@ACIIL still wanting this feature?

**Comment by ACIIL** [comment]
Oh wow its been so long since contributing. I kinda forgot everything.
(reviews posts here)

The problem was all the evolution mechanics needed a clean data pipeline and a lot of match data was wasted when fitting huge chunks of saved data. So i brought up what needed changes for what is and isnt saved and how much for every match.

Yeah consistent stats and how they are saved is important and a oversight from back than years ago as it was snuck in deep and away from end user awareness. I'm not really sure where the saltbot project is today.

I hope my old fork improving the evolution mechanics on the weight chromosomes was useful. Last i tried running saltbot a year ago my chromium build couldn't load the saltbot addon and then had errors running my old separate fork. I'm not really able to pick up were we left off.

**Comment by calexil** [comment]
@ACIIL you have some catching up to do on your fork, any plans to implement the suggested changes?
