### ISSUE TITLE
Add a redirect in popup.ts to make sure the sure is on the correct saltybet.com website (not live.saltybet.com)

### ISSUE THREAD

**Issue by RyTak** [saltbot-org/saltbot#226]
Unable to import either file, nor change any aspect of the UI or secondary window.

Returns error: "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist." from popup.html:1

Twitch chat tab does not open either.

Unsure how to reproduce due to it happening at this stage of use. Hopefully the error printout helps.

**Comment by calexil** [comment]
please check that any adblockers and privacy extensions are not blocking the app

**Comment by RyTak** [comment]
saltbot is the only extension installed in chrome. i use FF as my primary browser.

**Comment by calexil** [comment]
hmm, can you fire up the inspector with f12 and open console and tell me what it's saying there?

**Comment by RyTak** [comment]
> Alarm delay is less than minimum of 1 minutes. Alarm "chromosome update" will fire in approximately 1 minutes.
popup.js:129 Attempting chromosome import...
popup.js:132 Upload successful.
popup.js:137 Attempting to read file...
popup.js:108 File read successful.
popup.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
popup.js:113 Attempting records import...
popup.js:116 Upload successful.
popup.js:121 Attempting to read file...
popup.js:103 File read successful.
2popup.html:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by RyTak** [comment]
found the cause. i was using live.saltybet.com/# as my bookmark. the bot recognized it as the correct URL.

maybe have it do a page redirect to the correct page if it fails to connect?

**Comment by calexil** [comment]
if
     location = 'https://live.saltybet.com/'
     window.location.replace('https://www.saltybet.com/')


should do it

**Comment by calexil** [comment]
not sure where it needs to be though

**Comment by calexil** [comment]
@reconman This should be an easy fix , but when I tried implementing the redirect it didn't work.

can you take a peek at my solution and add it where needed:

if
 location = 'https://live.saltybet.com/'
 window.location.replace('https://www.saltybet.com/')

**Comment by reconman** [comment]
I would personally not do a redirect in case anyone wants to bet on Evo matches. That's what the `live.saltybet.com` page is for.

**Comment by calexil** [comment]
closed due to non-issue
