### ISSUE TITLE
Build Failure SyntaxError: Unexpected token "{" on multiple lines

### ISSUE THREAD

**Issue by calexil** [saltbot-org/saltbot#324]
Full build error log here:
https://dpaste.com/FP57REW6Z

Multiple syntax failures

**Comment by reconman** [comment]
Where do you get the errors?

**Comment by calexil** [comment]
in terminal after entering: npm install && npm run build

**Comment by reconman** [comment]
I don't think you have a clean version. I can build it on my machine just fine. The builds on Github run fine, too.

**Comment by calexil** [comment]
Log from the build crash:

https://dpaste.com/HJNL69LRT

**Comment by calexil** [comment]
RESOLVED: needed the latest version of nodejs

fixed by following this:

https://github.com/nodesource/distributions/blob/master/README.md#debinstall
