### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by calexil** [saltbot-org/saltbot#397]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

js/contentscript.js:1439 (anonymous function)

**Comment by reconman** [comment]
Give me more info please:

1. When does it happen?
2. How often does it happen?
3. Which version of saltbot are you using? master or last release?

**Comment by calexil** [comment]
1: Constant, begins at launch
2: see above
3: master

**Comment by reconman** [comment]
Can't reproduce it on my end. It happens when it's trying to read the part below the video with the character names and the bet button.
