### ISSUE TITLE
Easy button names

### ISSUE THREAD

**Issue by Vehdrehl** [saltbot-org/saltbot#398]
As accurate as they may be from a technical standpoint, the **update generic weights** and **reset pool** buttons aren't clear for a layman, at all. I'd love to see an option to make what these do clear, with a preference for a tooltip on mouseover.

**Comment by reconman** [comment]
If you know HTML, you could submit a PR.

> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

**Comment by calexil** [comment]
I know html and will look into adding some popouts to clarify the buttons, good suggestion @Vehdrehl

**Comment by Vehdrehl** [comment]
A popout window for the messages so that you can switch tabs etc would be a great feature too
