### ISSUE TITLE
Feature: automatic crash detection

### ISSUE THREAD

**Issue by synkarius** [saltbot-org/saltbot#4]
Write a separate extension which runs in another specified tab, uses messaging to periodically check for a pulse from selected tabs, if no response comes, reopen those tabs.

**Comment by reconman** [comment]
Somehow on each refresh the Monk mode is activated. Could you fix that please?

**Comment by synkarius** [comment]
New issue opened for this problem:
https://github.com/synkarius/saltbot/issues/32
