### ISSUE TITLE
Saltbot in Chrome is officially dead

### ISSUE THREAD

**Issue by reconman** [saltbot-org/saltbot#508]
I recently tried uploading version 2.6.7 to the Chrome web store and it was rejected because it supposedly violates the Content Policy against Gambling.

I appealed, but they still insisted that it's gambling. There is nothing further I can do at this point.

Also, I haven't used this extension for 5 years and there's nobody else who is willing and able to fix bugs and develop new features.

I will leave saltbot in the chrome store for now, but I can't fix bugs any longer.

**Comment by calexil** [comment]
That's, unfortunate. But at least someone in the future can access 2.6.6 and pick up the puzzle. Thank you for all your hard work reconman. I and all the other saltbotters out there truly appreciate it.

**Comment by reconman** [comment]
Made it work in Firefox, so it lives on.
