### ISSUE TITLE
All matches being marked as having "Tier: U" and "Odds: U"

### ISSUE THREAD

**Issue by Dziugaske** [saltbot-org/saltbot#513]
![image](https://user-images.githubusercontent.com/42064096/189543111-6745f03e-edb6-4733-9061-ce07bc496b4e.png)
Using the current Firefox extension, all matches are being incorrectly recorded. This is on a fresh install of Firefox and SaltBot extension.

**Comment by reconman** [comment]
I didn't notice because this error doesn't happen with BetterTTV and FrankerFaceZ installed. Fixed in 2.7.3.
