### ISSUE TITLE
Not writing correctly in database

### ISSUE THREAD

**Issue by SirJazz** [saltbot-org/saltbot#521]
The bot is chosing Tier U for every fight, no matter what:

Match result:
Character 1: Rea katori EX7
Character 2: Ramda EX3
Winner: Rea katori EX7
Strategy: rc
Prediction: Predicted correctly
Tier: U
Mode: m
Odds: U
Length of match in seconds: 0

**Comment by reconman** [comment]
Should be fixed with 2.7.5. Please report back.

@FuzzyRamen You reported the same problem.

**Comment by SirJazz** [comment]
fixed

**Comment by FuzzyRamen** [comment]
Looks good so far.

**Comment by SirJazz** [comment]
He is doing it again, every fight is Tier: U

**Comment by SirJazz** [comment]
Interesting... he stopped doing it after ~10 fights
